// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ED1
arma::mat ED1(const arma::mat& x);
RcppExport SEXP SC3_ED1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    __result = Rcpp::wrap(ED1(x));
    return __result;
END_RCPP
}
// ED2
NumericMatrix ED2(const NumericMatrix& x);
RcppExport SEXP SC3_ED2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    __result = Rcpp::wrap(ED2(x));
    return __result;
END_RCPP
}
// consmx
arma::mat consmx(const arma::mat dat);
RcppExport SEXP SC3_consmx(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat >::type dat(datSEXP);
    __result = Rcpp::wrap(consmx(dat));
    return __result;
END_RCPP
}
// norm_laplacian
arma::mat norm_laplacian(arma::mat A);
RcppExport SEXP SC3_norm_laplacian(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    __result = Rcpp::wrap(norm_laplacian(A));
    return __result;
END_RCPP
}
// tmult
arma::mat tmult(arma::mat x);
RcppExport SEXP SC3_tmult(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    __result = Rcpp::wrap(tmult(x));
    return __result;
END_RCPP
}
