# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splits <- function(myString) {
    .Call('SC3_splits', PACKAGE = 'SC3', myString)
}

calcPWD1 <- function(x) {
    .Call('SC3_calcPWD1', PACKAGE = 'SC3', x)
}

calcPWD2 <- function(x) {
    .Call('SC3_calcPWD2', PACKAGE = 'SC3', x)
}

consmx <- function(myString, res, length) {
    .Call('SC3_consmx', PACKAGE = 'SC3', myString, res, length)
}

mult <- function(D, x, dim) {
    .Call('SC3_mult', PACKAGE = 'SC3', D, x, dim)
}

